server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.98.37.67:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Zongs_365
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

